### ISSUE TITLE
Issues building with Maya 2024.2

### ISSUE THREAD

**Issue by dgovil** [Autodesk/bifrost-usd#23]
I'm trying to update to Maya 2024.2 and am hitting some CMake errors within Bifrost 2.7.1.1 that are new to me

Using 0e5968b90d535bb2e4b0765c16bda937b75f11b6 as the commit I'm building from, I get the following errors

```
CMake Warning at /usr/local/apps/maya/2024.2-a0/apple_universal/Applications/Autodesk/bifrost/maya2024/2.7.1.1/bifrost/sdk/cmake/cpp2json.cmake:81 (message):
   Please specify a TARGET
Call Stack (most recent call first):
  cmake/utils.cmake:139 (amino_cpp2json)
  src/BifrostUsd/include/CMakeLists.txt:43 (bifusd_header_parser)


CMake Error at /usr/local/apps/maya/2024.2-a0/apple_universal/Applications/Autodesk/bifrost/maya2024/2.7.1.1/bifrost/sdk/cmake/cpp2json.cmake:84 (message):
   No input header file was specified with INPUT.
Call Stack (most recent call first):
  cmake/utils.cmake:139 (amino_cpp2json)
  src/BifrostUsd/include/CMakeLists.txt:43 (bifusd_header_parser)
```

My build args are as follows to the CMake file:

```
-DCMAKE_BUILD_TYPE=RelWithDebInfo
-DMAYA_RUNTIME_LOCATION=/usr/local/apps/maya/2024.2-a0/apple_universal/Applications/Autodesk/maya2024
-DBIFROST_LOCATION=/usr/local/apps/maya/2024.2-a0/apple_universal/Applications/Autodesk/bifrost/maya2024/2.7.1.1/bifrost
-DBIFUSD_PACKAGE_NAME=bifrost_usd_pack
-DUSD_LOCATION=/usr/local/apps/usd/internal-0.23.11-a1/maya-2024.2-a0
-DCMAKE_INSTALL_PREFIX=/usr/local/apps/bifrost_usd/local-1.2.1-a0/maya-2024.2-a0/python-3.10
-DCMAKE_VERBOSE_MAKEFILE=TRUE
-DBIFUSD_USE_PYTHON_VERSION=3
-DPYTHON3_LIBRARY=/usr/local/apps/python/3.10.8-a0/apple_universal-2/Python.framework/Versions/3.10/lib/libpython3.10.dylib
-DPYTHON3_EXECUTABLE=/usr/local/apps/python/3.10.8-a0/apple_universal-2/Python.framework/Versions/3.10/bin/python3
-DPYTHON_INCLUDE_DIR=/usr/local/apps/python/3.10.8-a0/apple_universal-2/Python.framework/Versions/3.10//include/python3.10
-DBIFUSD_OSX_MIN_OS=13.3
-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64
-DBIFUSD_OSX_BINARY_ARCH=ub2
```

The amino_cpp2json function is called with these args
```
amino_cpp2json(generate_usd_type_json
  CPP2JSON $<TARGET_FILE:Bifrost::cpp2json>
  DESTINATION  /Users/dhruvgovil/Projects/bifrost-usd/cmake-build-debug/common/resources/json
  OUT_VAR node_def_jsons
  DEFINITIONS DISABLE_PXR_HEADERS
  HEADER_FILES;Attribute.h;Layer.h;Prim.h;Stage.h;Enum.h;LINK_LIBS;usdHeadersInstall)
```

Looking at https://github.com/Autodesk/bifrost-usd/blob/dev/cmake/utils.cmake#L139, I don't see an `INPUT` parameter being passed in, which makes sense why the function would error. 

If I revert the commit it came from (https://github.com/Autodesk/bifrost-usd/pull/21) it builds with Maya 2024.2

**Comment by frenchdog** [comment]
Hi @dgovil, using https://github.com/Autodesk/bifrost-usd/commit/0e5968b90d535bb2e4b0765c16bda937b75f11b6 requires Bifrost 2.8.0.0.

To build against Bifrost 2.7.1.1 you will need to checkout the tag `bifrost-2.7.1.0` in this repo (there is no bifrost-2.7.1.1 tag since there are no changes on the bifrost-usd side in Bifrost 2.7.1.1).

But I would strongly recommend to install Bifrost 2.8.0.0 for Maya 2024.2 instead, so you will be able to build from the `bifrost-2.8.0.0`tag.

[Bifrost 2.8.0.0](https://help.autodesk.com/view/BIFROST/ENU/?guid=Bifrost_ReleaseNotes_release_notes_release_notes_2_8_0_0_html) is a major feature release with new capabilities, and performance improvements. It is available for Maya 2022, 2023, and 2024 from the [Autodesk Accounts Portal](https://manage.autodesk.com/).

Here are the info to download Bifrost 2.8.0.0 for Maya
Log in to your [Autodesk Account](https://manage.autodesk.com/).
Select Product Updates (along the left bar).
Select the Extensions tab (along the top).
If you don't see the Bifrost version you want, you might need to change the time range under Release date at right.
If the list is long, you can enter Bifrost in the search box.
Click the Download button next to the version of Bifrost that you want for your version of Maya and operating system.

**Comment by dgovil** [comment]
Ah okay, I didn't notice the tagging change included the bifrost compatibility. 

Thanks, I'll try and get the new bifrost deployed.
